name: fupa_aliados
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  appcenter: ^0.2.1
  appcenter_analytics: ^0.2.1
  appcenter_crashes: ^0.2.1
  cached_network_image: null
  connectivity: ^3.0.6
  cool_stepper: ^1.2.1
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.0
  dartz: ^0.9.2
  dio: ^3.0.10
  equatable: ^2.0.2
  file_picker: ^2.1.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  flutter_spinkit: ^4.1.2
  flutter_svg: ^0.22.0
  flutter_widget_from_html_core: ^0.6.1+4
  focus_widget: ^1.0.5+2
  font_awesome_flutter: ^9.0.0
  get: ^4.1.4
  google_fonts: null
  image_picker: 0.6.7+22
  intl: ^0.17.0
  logger: ^1.0.0
  mask_text_input_formatter: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  open_store: ^0.2.4
  package_info: ^2.0.2
  photo_view: ^0.12.0
  pin_code_fields: ^6.1.0
  reactive_forms: ^10.4.1
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.jpg"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Candara
      fonts:
        - asset: assets/fonts/Candara/Candara.ttf
          weight: 400

  assets:
    - assets/images/
